### ISSUE TITLE
DB Model - User

### ISSUE THREAD

**Issue by cpuell** [mk0/infectionchain_tracking#1]

**Comment by cpuell** [comment]
Example script:

CREATE TABLE `user` (
  `id` varchar(32) NOT NULL,
  `date_create` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `date_create_timezone` varchar(255) DEFAULT NULL,
  `date_update` datetime DEFAULT NULL,
  `date_update_timezone` varchar(255) DEFAULT NULL,
  `email` varchar(250) DEFAULT NULL,
  `email_verification_status` bit(1) DEFAULT NULL,
  `email_verification_token` varchar(255) DEFAULT NULL,
  `encrypted_password` varchar(255) DEFAULT NULL,
  `is_delete` bit(1) NOT NULL DEFAULT b'0',
  `is_enabled` bit(1) NOT NULL DEFAULT b'1',
  `user_create` varchar(32) DEFAULT NULL,
  `user_update` varchar(32) DEFAULT NULL,
  `username` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by mk0** [comment]
> 
> 
> Example script:
> 
> CREATE TABLE `user` (
> `id` varchar(32) NOT NULL,
> `date_create` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
> `date_create_timezone` varchar(255) DEFAULT NULL,
> `date_update` datetime DEFAULT NULL,
> `date_update_timezone` varchar(255) DEFAULT NULL,
> `email` varchar(250) DEFAULT NULL,
> `email_verification_status` bit(1) DEFAULT NULL,
> `email_verification_token` varchar(255) DEFAULT NULL,
> `encrypted_password` varchar(255) DEFAULT NULL,
> `first_name` varchar(120) DEFAULT NULL,
> `is_delete` bit(1) NOT NULL DEFAULT b'0',
> `is_enabled` bit(1) NOT NULL DEFAULT b'1',
> `last_name` varchar(250) DEFAULT NULL,
> `user_create` varchar(32) DEFAULT NULL,
> `user_id` varchar(255) DEFAULT NULL,
> `user_update` varchar(32) DEFAULT NULL,
> `username` varchar(120) DEFAULT NULL,
> PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

- Timestamps kann man direkt mit Offset speichern (TIMESTAMP WITH TIME ZONE)
- encrypted_password würde ich mit 256 Zeichen speichern, um SHA256 Encryption zu verwenden.
- last_name würde ich wie first_name auch auf 120 Zeichen begrenzen
- is_deleted: Nach DSGVO müssen Accountdaten gelöscht werden, wenn der Benutzer seinen Account löscht.

**Comment by cpuell** [comment]
@mk0  **Timestamps  / offset** denke es ist einfacher wenn das BE dir die Daten via swagger als separate einträge gibt, andernfalls muss FE das auseinander casten wenn wir ne tabelle machen und Datum und Uhrzeit als **sort** und **search** machen. Einfacher für server side search and sort.

**Comment by cpuell** [comment]
@mk0 **last_name** und **first_name** sind in spanischen ländern durchaus länger als 120 char, gerade bei doppel vornamen in spanien. Daher mein Vorschlag mit 250 char.

**Comment by mk0** [comment]
> 
> 
> @mk0 **Timestamps / offset** denke es ist einfacher wenn das BE dir die Daten via swagger als separate einträge gibt, andernfalls muss FE das auseinander casten wenn wir ne tabelle machen und Datum und Uhrzeit als **sort** und **search** machen. Einfacher für server side search and sort.

Dann bekomme ich im Backend mit SQL-Vergleiche auf Zeitstempel Probleme. Zumal existieren doch Date-Bibliotheken auch im Frontend, die das verarbeiten können, oder nicht?

**Comment by mk0** [comment]
> 
> 
> @mk0 **last_name** und **first_name** sind in spanischen ländern durchaus länger als 120 char, gerade bei doppel vornamen in spanien. Daher mein Vorschlag mit 250 char.

Ok, verstanden

**Comment by cpuell** [comment]
> > @mk0 **Timestamps / offset** denke es ist einfacher wenn das BE dir die Daten via swagger als separate einträge gibt, andernfalls muss FE das auseinander casten wenn wir ne tabelle machen und Datum und Uhrzeit als **sort** und **search** machen. Einfacher für server side search and sort.
> 
> Dann bekomme ich im Backend mit SQL-Vergleiche auf Zeitstempel Probleme. Zumal existieren doch Date-Bibliotheken auch im Frontend, die das verarbeiten können, oder nicht?

verstehe.. da bin ich flexible.. können es natürlich auch zusammenlegen.
